// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.startupRolloutPrefs.browser.partnerlink.useAttributionURL", true);
user_pref("app.normandy.startupRolloutPrefs.browser.topsites.experiment.ebay-2020-1", true);
user_pref("app.normandy.startupRolloutPrefs.browser.topsites.useRemoteSetting", true);
user_pref("app.normandy.startupRolloutPrefs.network.jar.record_failure_reason", false);
user_pref("app.normandy.user_id", "04717d5a-ea98-4934-a2d5-18956a146034");
user_pref("app.update.auto.migrated", true);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1619023618);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1619023596);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1619023593);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1619023648);
user_pref("app.update.lastUpdateTime.telemetry_untrustedmodules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("app.update.migrated.updateDir2.308046B0AF4A39CB", true);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1619023587);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.launcherProcess.enabled", true);
user_pref("browser.migration.version", 107);
user_pref("browser.newtabpage.activity-stream.impressionId", "{a2c9831d-d2bf-421d-b39f-56235e91acdb}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"shareURL\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.region.update.updated", 1619023592);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1619023648290");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1619025459290");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1619023599460");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1619045199460");
user_pref("browser.search.region", "BR");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1619023592");
user_pref("browser.slowStartup.averageTime", 9004);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20210318103112");
user_pref("browser.startup.homepage_override.mstone", "87.0");
user_pref("browser.startup.lastColdStartupCheck", 1619023591);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\",\"jid1-niffy2ca8fy1tg_jetpack-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"jid1-niffy2ca8fy1tg_jetpack-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1619023594168");
user_pref("devtools.webextensions.jid1-NIfFY2CA8fy1tg@jetpack.enabled", true);
user_pref("distribution.iniFile.exists.appversion", "87.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("dom.push.userAgentID", "486095ff721a4f3eb8c1e0c43b5864bc");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210318103112");
user_pref("extensions.lastAppVersion", "87.0");
user_pref("extensions.lastPlatformVersion", "87.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.extension.hidden", false);
user_pref("extensions.ui.lastCategory", "addons://discover/");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.webcompat.enable_picture_in_picture_overrides", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.jid1-NIfFY2CA8fy1tg@jetpack", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"adc73dd3-13ca-4ea8-9e3b-27e27cda5aee\",\"formautofill@mozilla.org\":\"d49d2ead-ed80-4a8a-b74a-14e4ffea367e\",\"screenshots@mozilla.org\":\"490c5750-f862-46cf-aebb-9a01f1be6a6d\",\"webcompat-reporter@mozilla.org\":\"b12c8534-b3be-40dd-82a0-f7de8974c6d7\",\"webcompat@mozilla.org\":\"3711bc15-6293-4921-8d63-be052f81cb0e\",\"default-theme@mozilla.org\":\"0917f499-416d-45f4-a7c7-7f07db7ba5d4\",\"google@search.mozilla.org\":\"ec7942ec-b6b1-4943-94d6-156bc2e03de6\",\"wikipedia@search.mozilla.org\":\"6660230e-4c15-474a-98b8-194ad121e75f\",\"mercadolivre@search.mozilla.org\":\"8398a0eb-1f11-4852-bb58-03eb225c8d39\",\"bing@search.mozilla.org\":\"437fc930-2811-4abf-96fe-2685d49d56d9\",\"ddg@search.mozilla.org\":\"051baa4f-85e8-4e13-b86f-242c4f6afe17\",\"jid1-NIfFY2CA8fy1tg@jetpack\":\"7426324a-b711-4c75-8122-974e0f4835d7\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1619023594);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gfx-shader-check.build-version", "20210318103112");
user_pref("gfx-shader-check.device-id", "0x5916");
user_pref("gfx-shader-check.driver-version", "27.20.100.8681");
user_pref("gfx.crash-guard.status.wmfvpxvideo", 2);
user_pref("gfx.crash-guard.wmfvpxvideo.appVersion", "87.0");
user_pref("gfx.crash-guard.wmfvpxvideo.deviceID", "0x5916");
user_pref("gfx.crash-guard.wmfvpxvideo.driverVersion", "27.20.100.8681");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("sanity-test.device-id", "0x5916");
user_pref("sanity-test.driver-version", "27.20.100.8681");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20210318103112");
user_pref("sanity-test.webrender.force-disabled", false);
user_pref("security.sandbox.content.tempDirSuffix", "{d25da75b-5b5f-4de0-b2dc-fb2fd2b6a8e8}");
user_pref("security.sandbox.plugin.tempDirSuffix", "{5509d61a-2235-4222-9f86-375a97f8e8cd}");
user_pref("toolkit.startup.last_success", 1619023581);
user_pref("toolkit.telemetry.cachedClientID", "62061b36-4167-4f3f-8859-dccef12c9fc4");
user_pref("toolkit.telemetry.previousBuildID", "20210318103112");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
user_pref("ui.osk.debug.keyboardDisplayReason", "IKPOS: Touch screen not found.");
